# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [60]:
#Instanciando expressões
a = 2.0 + 3.0 / 5.0
b = (a + 10.2) - 5.0 * 2.0
c = a / b + 33.8
d = a / (b+c)
e = d * 2

#Imprimindo resultados
print(f'a = {a}')
print(f'b = {b}')
print(f'c = {c}')
print(f'd = {d}')
print(f'e = {e}')

a = 2.6
b = 2.799999999999999
c = 34.72857142857143
d = 0.0692805481537876
e = 0.1385610963075752

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [61]:
#Instanciando expressões
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
lista_b = lista_a * 2
lista_c = lista_a + lista_b
#lista_d = lista_a / (lista_b * lista_c) -> Não é possível multiplicar uma lista por outra

#Imprimindo resultado das listas
print(f"lista_a = {lista_a}")
print(f"lista_b = {lista_b}")
print(f"lista_c = {lista_c}")
print(f"lista_d = Não é possível multiplica ou dividir uma lista por outra")

lista_a = [2.0, 3.0, 5.0, 10, 20, 30]
lista_b = [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
lista_c = [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
lista_d = Não é possível multiplica uma lista por outra

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [62]:
#Instanciando lista
lista = [a, b, c, d, e]
lista_r2 = [a**0.5, b**0.5, c**0.5, d**0.5, e**0.5]
lista_final = lista + lista_r2

#Imprimindo a última lista
lista_final

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752,
 1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [63]:
#Importando numpy
import numpy as np

#Duplicando lista_final
dup = lista_final*2

#Convertendo para np.array
array_dup = np.array(dup)

#Remodelando
array_dup = np.reshape(array_dup, (5,4))

#Imprimindo array
array_dup

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [64]:
lista_med = array_dup.mean(axis=0)
lista_med = lista_med.tolist()
lista_med

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [65]:
#Calculando o número total de elementos
elem = array_dup.shape[0]*array_dup.shape[1]

#Imprimindo o número total de elementos
print(f"O array possui {elem} elementos")

#Adicionando a lista de médias na array
array_med = np.append(array_dup, [lista_med],axis =0)

#Imprimindo array resultante
array_med

O array possui 20 elementos

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [74]:
#Importando pandas
import pandas as pd

#Remodelando array -> Mesmo resultado do que array_med
array_col = array_med.reshape(-1,4)

#Convertendo para dataframe
df = pd.DataFrame(array_col)

#Arredondando valores
df = df.round(3)

#Imprimindo dataframe
df

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [77]:
#Instanciando lista de média das linhas
lista_linhas_med = df.mean(axis=1)

#Adicionando no df
df[4] = lista_linhas_med

#Imprimindo df
df

        0      1       2      3         4
0   2.600  2.800  34.729  0.069  10.04950
1   0.139  1.612   1.673  5.893   2.32925
2   0.263  0.372   2.600  2.800   1.50875
3  34.729  0.069   0.139  1.612   9.13725
4   1.673  5.893   0.263  0.372   2.05025
5   7.881  2.149   7.881  2.149   5.01500

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [101]:
#Última coluna
desc_col = df.iloc[:, -1].describe()

#Transpondo df
transp = df.transpose()

#Última linha do df original
desc_lin = transp.iloc[:, -1].describe()

#Imprimindo resultado
print(desc_col)
print(desc_lin)

count     6.000000
mean      5.015000
std       3.758615
min       1.508750
25%       2.120000
50%       3.672125
75%       8.106688
max      10.049500
Name: 4, dtype: float64
count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [113]:
#Editando nome das colunas
df = df.rename(columns = {4:'Médias'})

#Editando nome do index
df = df.rename(index = {5:'Médias'})

#Imprimindo df ajustado
print(df)

#Média das médias
med_med = df.iloc[-1,-1]

#Imprimindo média das médias
print(f"A média das médias é {med_med}")

             0      1       2      3    Médias
0        2.600  2.800  34.729  0.069  10.04950
1        0.139  1.612   1.673  5.893   2.32925
2        0.263  0.372   2.600  2.800   1.50875
3       34.729  0.069   0.139  1.612   9.13725
4        1.673  5.893   0.263  0.372   2.05025
Médias   7.881  2.149   7.881  2.149   5.01500
A média das médias é 5.015000000000001