# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Uma matriz pode receber um vetor.

In [ ]:
#instanciando uma matriz
matriz = [[1,2,3],[4,5,6],[7,8,9]]

#Imprimindo a matriz inicial
print(f"A matriz inicial é: {matriz}")

#Adicionando o vetor na matriz
matriz.append([10,11,12])

#Imprimindo a matriz ffinal
print(f"A matriz final é: {matriz}")

A matriz inicial é: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
A matriz final é: [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [ ]:
#Instanciando novamente a lista de genes
genes = ["adeI","oxa-23","arr","sul","adeN"]

#Instanciando as listas
gene_1 = [4, 'ad', 1, False]
gene_2 = [6, 'ox', 1, False]
gene_3 = [3, 'ar', 1, False]
gene_4 = [3, 'su', 0, False]
gene_5 = [4, 'ad', 1, False]

#Instanciando matriz
genes_matriz = [gene_1, gene_2, gene_3, gene_4, gene_5]

#Imprimindo matriz
genes_matriz

[[4, 'ad', 1, False],
 [6, 'ox', 1, False],
 [3, 'ar', 1, False],
 [3, 'su', 0, False],
 [4, 'ad', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [ ]:
#importando numpy
import numpy as np

#Transformando matriz em array
array = np.array(genes_matriz)

#Imprimindo array
array

array([['4', 'ad', '1', 'False'],
       ['6', 'ox', '1', 'False'],
       ['3', 'ar', '1', 'False'],
       ['3', 'su', '0', 'False'],
       ['4', 'ad', '1', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [ ]:
#Chamando dados do terceiro gene
array_genes = array[2]

#Imprimindo resultado
print(f"Os dados do gene {genes[2]} são: {array_genes}")

Os dados do gene arr são: ['3' 'ar' '1' 'False']

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [ ]:
#Localizando informações 'hu'
array_hu = array[:,3]

#Imprimindo resultado
print(f"Os genes {genes} tem 'hu'? {array_hu}")

Os genes ['adeI', 'oxa-23', 'arr', 'sul', 'adeN'] tem 'hu'? ['False' 'False' 'False' 'False' 'False']

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [ ]:
#Localizando o segundo e quarto gene, além de verificar o número de caracteres e de 'a' neles
array_2_4 = array[[1,3],1:3]

#Imprimindo resultado
print(array_2_4)

[['ox' '1']
 ['su' '0']]

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [124]:
#Importando pandas
import pandas as pd

#Instanciação do dicionario
dicionario_final = ({'adeI': [4, 'ad', 1, False],
                     'oxa-23': [6, 'ox', 1, False],
                     'arr': [3, 'ar', 1, False],
                     'sul': [3, 'su', 0, False],
                     'adeN': [4, 'ad', 1, False]})

#Transformando array em dataframe
df = pd.DataFrame(dicionario_final).T

#Nomeando colunas
df.columns = ['n_caracteres', 'inicio_genes','num_de_a','hu_no_nome']
df

       n_caracteres inicio_genes num_de_a hu_no_nome
adeI              4           ad        1      False
oxa-23            6           ox        1      False
arr               3           ar        1      False
sul               3           su        0      False
adeN              4           ad        1      False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [125]:
#Recuperando o número de caracteres e de 'a' de cada gene
df_a = df.iloc[:,[0,2]]

#Imprimindo o número de caracteres e de 'a' em cada gene
df_a

       n_caracteres num_de_a
adeI              4        1
oxa-23            6        1
arr               3        1
sul               3        0
adeN              4        1

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [126]:
#Verificando a presença de 'hu' no primeiro e terceiro gene
df1 = df.iloc[[0,2],-1]

#Imprimindo se há presença de 'hu' no primeiro e terceiro gene
df1

adeI    False
arr     False
Name: hu_no_nome, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [127]:
#Importando tabela
df_seguro = pd.read_csv('data.csv')

#Número de entradas
n_ent = df_seguro.shape[0]

#Classe das colunas
colunas = list(df_seguro.dtypes)

#Número de elementos por classe
elem_classe = df_seguro.dtypes.value_counts().to_list()

#Determinando a média
med = df_seguro.iloc[:,[0,3,8]].mean().to_list()

#Determinando o desvio padrão
dp = df_seguro.iloc[:,[0,3,8]].std().to_list()

#Determinando o terceiro quartil
q3 = df_seguro.iloc[:,[0,3,8]].quantile(0.75).to_list()

#Criando dicionário
dicionario = {'Número de entradas': n_ent,
              'Classe das colunas': colunas,
              'Número de elementos por classe': elem_classe,
              'Média': med,
              'Desvio padrão': dp,
              'Terceiro quartil': q3}

#Imprimindo dicionário
dicionario

{'Número de entradas': 36634,
 'Classe das colunas': [dtype('int64'),
  dtype('O'),
  dtype('O'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('int64'),
  dtype('float64'),
  dtype('float64'),
  dtype('O'),
  dtype('O'),
  dtype('int64')],
 'Número de elementos por classe': [11, 4, 3],
 'Média': [548661.9371894961, 731478.0068460993, 2571004.0973420865],
 'Desvio padrão': [259912.9264939017, 17523003.588415045, 20367766.5691781],
 'Terceiro quartil': [774252.0, 0.0, 1128871.1824999999]}